### ISSUE TITLE
自己搭建的话求个教程

### ISSUE THREAD

**Issue by wujinpai** [sunls24/temporary-mail#1]
可以写个教程吗🥺

**Comment by muziqiu2** [comment]
同求，有没有部署文档呀

**Comment by sunls24** [comment]
https://github.com/sunls24/temporary-mail/issues/2#issuecomment-1950896647

1. 域名需要放在 cloudflare 托管并开启邮件转发功能，Catch-All 转发至自己常用的邮箱
2. 设置一个邮件规则，将接收地址是对应域名的邮件都移动至垃圾邮件文件夹中
3. Fork 仓库然后修改这行代码，填写自己的域名，不要忘记`@`
https://github.com/sunls24/temporary-mail/blob/9f875c9af92a726109328920ba1390bb50ae611e/lib/constant.ts#L1
4. 在 [Vercel](https://vercel.com) 部署，需设置环境变量 `IMAP_USER` `IMAP_PASS`
`IMAP_HOST` (默认: outlook.office365.com)
`IMAP_PORT` (默认: 993)

**Comment by sunls24** [comment]
@afycn @muziqiu2 

[自建部署教程](https://github.com/sunls24/temporary-mail/blob/main/deploy.md)
