### ISSUE TITLE
这个项目目前是不是未完成呢？我看似乎没监听25端口   没法收到邮件

### ISSUE THREAD

**Issue by itq5** [sunls24/temporary-mail#2]
这个项目目前是不是未完成呢？我看似乎没监听25端口   没法收到邮件

**Comment by itq5** [comment]
大佬，你这边是怎么把项目和cloudflare里面的邮箱服务关联起来的呢？求教，感谢！

**Comment by sunls24** [comment]
<img width="1395" alt="image" src="https://github.com/sunls24/temporary-mail/assets/57647932/cfc920c0-6e46-4e9d-b27c-e34b3da4f256">

我是使用 cloudflare 的邮件转发功能，将接收到的所有邮件转发到目标邮箱中，然后本程序会向目标邮箱中获取邮件，部署时需要配置目标邮箱的`IMAP_HOST`, `IMAP_PORT`,  `IMAP_USER`, `IMAP_PASS`

默认会从垃圾邮件 Junk 文件夹中获取，可通过 `IMAP_PATH` 环境变量指定。

使用默认的配置需要添加这一个规则

<img width="886" alt="image" src="https://github.com/sunls24/temporary-mail/assets/57647932/b41b415a-7133-4e02-9137-87957690bb41">

**Comment by sunls24** [comment]
@itq5 

[自建部署教程](https://github.com/sunls24/temporary-mail/blob/main/deploy.md)
